---
title: Auditore Website
timezone: UTC
collections:
  for_sale:
    title: For Sale
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wips:
    title: Wips
    output: false
name: Auditore Custom Instruments
source: "."
destination: "./_site"
collections_dir: "."
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass
safe: false
include:
- ".htaccess"
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: false
show_drafts: 
limit_posts: 0
future: false
unpublished: false
whitelist: []
plugins: []
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
detach: false
port: 4000
host: 127.0.0.1
baseurl: ""
show_dir_listing: false
permalink: date
paginate_path: "/page:num"
quiet: false
verbose: false
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false
rdiscount:
  extensions: []
redcarpet:
  extensions: []
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
