* Auditore Custom Instruments website
	All functionality not included in Prologue template (see information below) or otherwise credited was implemented by Dennis Zarger.
	
** Credits
*** Images
	Demo images credited to the kind community at www.pixabay.com
 
	Photos of Auditore guitars credit to Evan Fife of Auditore Custom Instruments
	
*** Other Assets & JavaScript Libraries
	JQuery Swipe-handling library credit to mattbryson (https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/)
	
	Jekyll static-site generator (https://jekyllrb.com/)
	
	(more included in Template Credits, see below)
	
	and thanks, as always, to w3schools.com & stackoverflow.com for their invaluable contributions to developers everywhere

*** Template Credit (lkn.io)
	Prologue by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)


	This is Prologue, a simple, single page responsive site template. It features a
	clean, minimalistic design and a sticky sidebar with navigation-linked scrolling.

	Demo content images* are courtesy of the ridiculously talented Felicia Simion. Check out
	more of her amazing work over at deviantART:

	http://ineedchemicalx.deviantart.com/

	(* = Not included! Only meant for use with my own on-site demo, so please do NOT download
	and/or use any of Felicia's work without her explicit permission!)

	Demo banner images* courtesy of Unsplash, a radtastic collection of CC0 (public domain)
	images you can use for pretty much whatever.

	(* = Not included)

	AJ
	aj@lkn.io | @ajlkn

	PS: Not sure how to get that contact form working? Give formspree.io a try (it's awesome).


**** Credits:
***** Demo Images:
	Felicia Simion (ineedchemicalx.deviantart.com)
	
	Unsplash (unsplash.com)

***** Icons:
	Font Awesome (fontawesome.io)

***** Other:
	jQuery (jquery.com)

	Scrollex (github.com/ajlkn/jquery.scrollex)
****** Responsive Tools (github.com/ajlkn/responsive-tools)
